#!/usr/bin/env bash
# Installs/Upgrades VGS Library

# Immediately exit on errors
set -euo pipefail

# DEFAULTS
VGS_URL='https://s3.amazonaws.com/vghn/vgs.tgz'
VGS_BAK_DIR="/tmp/vgs_backup_$(date +%Y%m%d)"
VGS_ROOT_DIR='/opt/vgs'
VGS_USER_DIR="${HOME}/vgs"

# Installs VGS Library
vgs_install(){
  if [[ $EUID == 0 ]]; then
    VGS_INSTALL_DIR=$VGS_ROOT_DIR
  else
    VGS_INSTALL_DIR=$VGS_USER_DIR
  fi

  if [[ -d "$VGS_INSTALL_DIR" ]]; then
    echo "Backing up existing directory to: ${VGS_BAK_DIR}"
    cp -rf "$VGS_INSTALL_DIR" "$VGS_BAK_DIR"; rm -rf "$VGS_INSTALL_DIR"
  fi

  echo "Downloading VGS Library to ${VGS_INSTALL_DIR}"
  mkdir -p "$VGS_INSTALL_DIR"
  wget -qO- "$VGS_URL" | tar xz -C "$VGS_INSTALL_DIR"
}
vgs_install
