#!/usr/bin/env bash
# Loads VGS

# DEBUG
[ -z "${DEBUG:-}" ] || set -x

# VARs
export VGS_DIR VGS_SHLIB VGS_TMP
VGS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
VGS_SHLIB="${VGS_DIR}/shlib"
VGS_TMP="$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')"

# Load VGS functions
export vgs_env_loaded
# set env loaded flag if not yet set
: vgs_env_loaded:"${vgs_env_loaded:=0}":
# increase load count counter
: vgs_env_loaded:$(( vgs_env_loaded+=1 )):

if [[ -d "$VGS_SHLIB" ]] && (( vgs_env_loaded == 1 )); then
  for file in ${VGS_SHLIB}/*.sh; do
    # shellcheck disable=1090
    . "$file"
  done
fi
